### ISSUE TITLE
want:  masscan,ssocks

### ISSUE THREAD

**Issue by ugksoft** [darkerego/binaries#1]
want:
 masscan,ssocks

**Comment by darkerego** [comment]
Masscan is tricky... I'll see what I can do.

**Comment by ugksoft** [comment]
i compile masscan ssocks OK!
ssocks ok
run masscan ,Immediately return, not work,no error :(

**Comment by ugksoft** [comment]
masscan  --help   run OK
masscan  -pxxx xxx  ,Immediately return, not work,no error :(may libpcap...)

**Comment by darkerego** [comment]
What is the endianess? Architecture? Board of machine you are trying to run it on? Build process or binary you used?

**Comment by darkerego** [comment]
Check out busybotnet ... https://github.com/isdrupter/busybotnet ...
