### ISSUE TITLE
the busybox binary was built on 2010 and copyrights come from 2009

### ISSUE THREAD

**Issue by xproot** [darkerego/binaries#13]
```
BusyBox v1.16.1 (2010-03-29 11:53:01 CDT) multi-call binary.
Copyright (C) 1998-2009 Erik Andersen, Rob Landley, Denys Vlasenko
and others. Licensed under GPLv2.
See source distribution for full notice.
```

**Comment by medvm** [comment]
You can [download ](https://busybox.net/downloads/binaries/1.28.1-defconfig-multiarch/busybox-mips) new version by yourself then

**Comment by xproot** [comment]
> medvm

Never saw these, thanks! Only found 2010 builds last time

**Comment by darkerego** [comment]
Take it up with the busybox developers,  I simply compiled it, what do you want from me lol?

**Comment by xproot** [comment]
> Take it up with the busybox developers,  I simply compiled it, what do you want from me lol?

I was kinda asking you to compile newer ones

**Comment by darkerego** [comment]
Unlikely to do that in the foreseeable future, but if I get some free time, considering the enormous amount of requests for new binaries and etc, perhaps I will
