### ISSUE TITLE
Protocol "https" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by GitUser200607** [darkerego/binaries#15]
Running **curl**  I get the error:
`curl: (1) Protocol "https" not supported or disabled in libcurl`

Linux 3.18.21-svn12205 mips

When I run it with _./curl_, I got the error:
`/bin/sh: ./curl: not found`

**Comment by darkerego** [comment]
Well, apparently I  didn't compile it with openssl. I can't see myself doing this again anytime soon, but if I do, I will totally take care of this for you.
