### ISSUE TITLE
Openvpn configure with --enable-pkcs11

### ISSUE THREAD

**Issue by Telefonorosso** [darkerego/binaries#3]
Hi!
Would that be possibile to build OpenVPN with pkcs11 (token) support?
My architecture is ELF 32-bit MSB  executable, MIPS, MIPS32 rel2 version 1
Many thanks,
Francesco Talarico

**Comment by darkerego** [comment]
I am certain it is possible. Unless you wanted to hire me to do it though this repository is ancient and I have no plans on doing this again soon. If that changes i will see what I can do .
