### ISSUE TITLE
MIPS 32 version 1 or MIPS-I version 1

### ISSUE THREAD

**Issue by mortegai** [darkerego/binaries#5]
Most of your binaries are for MIPS32 rel2 version 1.
I am interested in tcpdump for MIPS 32 version 1 or MIPS-I version 1 (like for example is busybox).
Please, can you please publish at least the compilation options used for tcpdump?
And I can compile it with my own cross toolchain.
Thank you

**Comment by darkerego** [comment]
Sure, most of this was compiled using [buildroot](https://buildroot.org/), and some was compiled in a chroot with debbootstap. I would suggest checking out buildroot first. When I get a chance im sure I can compile a static tcpdump for you if you want

**Comment by trogalko** [comment]
Will your binaries will run on ingenic T20 (MIPS32 ISA) , [http://www.ingenic.com.cn/en/?product/id/14.html](url)  .
Currently at work, will try it at home.

**Comment by darkerego** [comment]
> Will your binaries will run on ingenic T20 (MIPS32 ISA) , [http://www.ingenic.com.cn/en/?product/id/14.html](url) . Currently at work, will try it at home.

If it's the same architecture it will, if not, it won't.
