### ISSUE TITLE
Instructions Request

### ISSUE THREAD

**Issue by romanianstrife** [darkerego/binaries#7]
Any chance you can provide us with Instructions to producing our own binaries so that we can submit pull requests?

**Comment by darkerego** [comment]
Sure. The easiest way to compile is to create a debian chroot with debootstrap and QEMU, and compile your binaries static from within the chroot.

**Comment by romanianstrife** [comment]
what is command compile statically

**Comment by darkerego** [comment]
https://en.wikipedia.org/wiki/Static_build
