### ISSUE TITLE
Binary Request: wget

### ISSUE THREAD

**Issue by romanianstrife** [darkerego/binaries#8]
I would love to have wget available as well

If you tell me how to compile these things statically, I would happily compile and create pull requests

**Comment by darkerego** [comment]
You could just use the mips busybox for this, but at some point I will get another chroot running and I will compile wget for you. Just give me a bit and I am certain I can do that for you. If you want to try it yourself, grab the latest buildroot toolkit, and run 

$ make wget

I believe is the command ... again, wget is present in almost all versions of busybox that you will find.

**Comment by domenukk** [comment]
> I believe is the command ... again, wget is present in almost all versions of busybox that you will find.

This might not be obvious to first time busybox users, but to emphasize this a bit: it is possible to `./busybox-mips wget` with the statically linked busybox from this repo. I don't think an extra wget is needed.

**Comment by OldLiu001** [comment]
Also you can view [my fork](https://github.com/OldLiu001/mips-binaries) for a departed 'wget' binary.

**Comment by NokiasSOFT** [comment]
Is there any recent wget for old kernel 2.6 mips32el?

**Comment by darkerego** [comment]
> > I believe is the command ... again, wget is present in almost all versions of busybox that you will find.
> 
> This might not be obvious to first time busybox users, but to emphasize this a bit: it is possible to `./busybox-mips wget` with the statically linked busybox from this repo. I don't think an extra wget is needed.

Good point. I was super busy at the time and totally missed that. Ofc wget is included.

**Comment by darkerego** [comment]
> > I believe is the command ... again, wget is present in almost all versions of busybox that you will find.
> 
> This might not be obvious to first time busybox users, but to emphasize this a bit: it is possible to `./busybox-mips wget` with the statically linked busybox from this repo. I don't think an extra wget is needed.

Thank you!
