### ISSUE TITLE
REQUEST FOR CONTACT AND HELP WITH COMPILING FOR MIPS ARCHITECTURE

### ISSUE THREAD

**Issue by Atropal1** [darkerego/binaries#9]
Nice to meet you

Is there any chance you could help me with compiling for MIPS architecture?
At the moment I specifically need program "pdftotext".
I tried to e-mail you, but I don't know if the e-mail address I found is valid...

Please let me know in any case :-)

Best regards

**Comment by darkerego** [comment]
Hi, how can I help you?

**Comment by darkerego** [comment]
Contact me at xelectron@protonmail.com

**Comment by darkerego** [comment]
> Contact me at [xelectron@protonmail.com](mailto:xelectron@protonmail.com)

Closing, you can still reach me at that email.
